version: 0.1.{build}
image: Visual Studio 2017
before_build:
  - nuget restore
build:
  project: Earcut.sln
  verbosity: minimal
test_script:
- cmd: nunit3-console \tests\bin\Earcut.dll --result=results.xml;format=AppVeyor